# Generated by Django 3.2.17 on 2023-02-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='artist',
            new_name='owner',
        ),
    ]
