# Generated by Django 3.2.17 on 2023-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_artist_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='style',
            field=models.CharField(choices=[
                ('Traditional', 'Traditional'),
                ('Neo-Traditional', 'Neo-Traditional'),
                ('Japanese', 'Japanese'),
                ('Realism', 'Realism'),
                ('Fineline', 'Fineline'),
                ('Blackwork', 'Blackwork'),
                ('Color', 'Color'),
                ('Script', 'Script'),
                ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
