# Generated by Django 3.2.17 on 2023-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='style',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('neo-traditional', 'Neo-Traditional'), ('japanese', 'Japanese'), ('realism', 'Realism'), ('fineline', 'Fineline'), ('blackwork', 'Blackwork'), ('color', 'Color'), ('script', 'Script'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
