# Generated by Django 3.2.17 on 2023-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                default='../default_post_ifegan', upload_to='images/'),
        ),
    ]
