# Generated by Django 3.2.17 on 2023-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../drilldown-removebg-preview_dxh3rz', upload_to='images/'),
        ),
    ]
