# Generated by Django 3.2.17 on 2023-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(),
        ),
    ]
