# Generated by Django 3.2.17 on 2023-02-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('satisfaction_rating', models.CharField(choices=[
                    ('highly recommends', 'Highly Recommend'),
                    ('somewhat recommends', 'Somewhat Recommend'),
                    ('does not recommend', 'Do Not Recommend')],
                    max_length=50)),
                ('artist', models.ForeignKey(limit_choices_to={
                 'is_artist': True},
                 on_delete=django.db.models.deletion.CASCADE,
                 related_name='artist', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
